### ISSUE TITLE
Add simple web GUI to upload custom symbols

### ISSUE THREAD

**Issue by nefarius** [nefarius/WinDbgSymbolsCachingProxy#137]
Recently I'm catching myself quite frequently using my LAN instance to upload custom symbols via Insomnia, which works but is not user-friendly at all.

Could use a simple Blazor server-side UI with an upload interface.

### Tasks

- [x] Add Blazor skeleton
- [x] Add auth
- [x] Add symbols search and filter page
- [ ] Add symbols upload page
